### ISSUE TITLE
DurableTask.Core.Exceptions.TaskFailedException: Exception of type 'DurableTask.Core.Exceptions.TaskFailedException' was thrown.

### ISSUE THREAD

**Issue by pschubert777** [microsoft/durabletask-dotnet#129]
Hello,

Currently developing durable functions using the net7 isolated process. I came across this error. It happens irregularly but it happens when I call the method `await Task.Delay(120000)` inside a transient service  and set the delay for 2 minutes. The purpose of doing this was to simulate an http call that takes roughly 2 minutes to execute. 

It seems to me that when this await Task.Delay(120000) is initiated, for some reason, the activity function that calls the method in the service that has this just quits abruptly and indicates the Task failed, not sure why. I have never come across this type of error before when developing azure functions in the past. 

I have linked the repo [ here](https://github.com/pschubert777/VideoProcessor---Copy)

You may have to  make a http request to this url http://localhost:7003/api/ProcessVideoStarter either (get or post request) it supports both. It takes in a query parameter of  a video name  (e.g. ?video=example.mp4)

Here is an example
 GET **http://localhost:7003/api/ProcessVideoStarter?video=example.mp4**

**_Outermost Exception_**

  **StackTrace:**

at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.<CallActivityAsync>d__25`1.MoveNext()
at VideoProcessor.OrchestratorFunctions.<ProcessVideoOrchestrator>d__1.MoveNext() in 
C:\Users\pschubert\source\repos\VideoProcessor\VideoProcessor\OrchestratorFunctions.cs:line 39

**Message**
Task 'ExtractThumbnail' (#1) failed with an unhandled exception: Exception while executing function: Functions.ExtractThumbnail

 **Failure Details**
              
**Source**
Microsoft.DurableTask.Worker          
                
**Name** 
EqualityContract = {Name = "TaskFailureDetails" FullName = "Microsoft.DurableTask.TaskFailureDetails"}

 **ErrorMessage**
"Exception while executing function: Functions.ExtractThumbnail"
                           
**ErrorType**
 "Microsoft.Azure.WebJobs.Host.FunctionInvocationException

**StackTrace**
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx 
instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper 
parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk- 
rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 352
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, 
  CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk- 
rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108

**InnermostException**
          
 **Source**
          
 DurableTask.Core

**Message**
Exception of type 'DurableTask.Core.Exceptions.TaskFailedException' was thrown.

 **StackTrace**
at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskInternal>d__21.MoveNext()
at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskToWorker>d__20`1.MoveNext()
at DurableTask.Core.TaskOrchestrationContext.<ScheduleTask>d__19`1.MoveNext()
at DurableTask.Core.RetryInterceptor`1.<Invoke>d__4.MoveNext()
at DurableTask.Core.RetryInterceptor`1.<Invoke>d__4.MoveNext()
 at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.<CallActivityAsync>d__25`1.MoveNext()
                                
                                
**Failure Details**
                    
 **Source**
 Microsoft.DurableTask.Worker

**Name** 
EqualityContract = {Name = "TaskFailureDetails" FullName = "Microsoft.DurableTask.TaskFailureDetails"}

**ErrorMessage**
Exception while executing function: Functions.ExtractThumbnail
                           
**ErrorType**
Microsoft.Azure.WebJobs.Host.FunctionInvocationException

****StackTrace****
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx 
instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper 
parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk- 
rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 352
at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance 
functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk- 
 rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108

**Comment by jviau** [comment]
Can you capture and share the original exception thrown from your activity? The exception details you shared are from the orchestrator. Since there is a serialization boundary between activity and orchestrator, most of the original exception information is gone (the stack trace being the important part we want here).

**Comment by jviau** [comment]
Also be aware there is a function timeout, where your functions may fail if they exceed this time: https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout

**Comment by jviau** [comment]
Closing due to inactivity.
