### ISSUE TITLE
Adopt the Functions Host gRPC server

### ISSUE THREAD

**Issue by bytemech** [microsoft/durabletask-dotnet#154]
Hi everyone, I'd like to raise this as an enhancement request. 

Back in 2020, the gRPC message limit was raised to `int.MaxValue` in [[pack]Increase gRpc Server max message size #5801](https://github.com/Azure/azure-functions-host/pull/5801) in the azure-functions-host runtime. 

However, Durable Functions persists with it's own implementation of gRPC, even though @jviau has mentioned that the intention is to remove this implementation. See:

- https://github.com/microsoft/durabletask-java/issues/137
- https://github.com/Azure/azure-functions-durable-js/issues/93 (It appears the JS implementation has raised the limit themselves on their implementation, which I'm not sure is gRPC-related) 

Currently trying to pass a large payload to an orchestration function (dotnet-isolated / 7) results in the following error:

`xecuted 'Functions.funcDurableFunctionsClient' (Failed, Id=71a2086b-78a8-44a9-afc6-5ab31fdfd706, Duration=1791ms)
[2023-06-11T09:43:27.402Z] System.Private.CoreLib: Exception while executing function: Functions.funcDurableFunctionsClient. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode="ResourceExhausted", Detail="Received message larger than max (43683498 vs. 4194304)"))
[2023-06-11T09:43:27.403Z]  ---> Grpc.Core.RpcException: Status(StatusCode="ResourceExhausted", Detail="Received message larger than max (43683498 vs. 4194304)")
[2023-06-11T09:43:27.403Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.ScheduleNewOrchestrationInstanceAsync(TaskName orchestratorName, Object input, StartOrchestrationOptions options, CancellationToken cancellation)
[2023-06-11T09:43:27.404Z]    at Example.DurableFunctions.DurableFunctionsClient.funcDurableFunctionsClient(HttpRequestData req, DurableTaskClient client, FunctionContext executionContext) in C:\Users\gloverb\src\durable-functions-example\src\DurableFunctionsHTTPClient.cs:line 31
[2023-06-11T09:43:27.405Z]    --- End of inner exception stack trace ---
[2023-06-11T09:43:27.406Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-06-11T09:43:27.406Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-06-11T09:43:27.407Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-06-11T09:43:27.408Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-06-11T09:43:27.409Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-06-11T09:43:27.410Z] --- End of stack trace from previous location ---
[2023-06-11T09:43:27.410Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-06-11T09:43:27.411Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-06-11T09:43:27.412Z] --- End of stack trace from previous location ---
[2023-06-11T09:43:27.412Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2023-06-11T09:43:27.413Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-11T09:43:27.414Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.Invoke(FunctionContext functionContext, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 22
[2023-06-11T09:43:27.415Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 82
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-06-11T09:43:27.416Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-06-11T09:43:27.417Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-06-11T09:43:27.417Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-06-11T09:43:27.418Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-06-11T09:43:27.419Z] --- End of stack trace from previous location ---
[2023-06-11T09:43:27.419Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-06-11T09:43:27.420Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-06-11T09:43:27.421Z] --- End of stack trace from previous location ---
[2023-06-11T09:43:27.421Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2023-06-11T09:43:27.422Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-11T09:43:27.423Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.Invoke(FunctionContext functionContext, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 22
[2023-06-11T09:43:27.424Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 82.`

**Comment by alievense** [comment]
We're currently facing the same problem when reading a 5MB output of an instance.
```
var instance = await client.GetInstancesAsync(instanceId, true);
```

**Comment by krishna-vijas** [comment]
Is there any workaround for this as of now?

**Comment by kemmis** [comment]
+1 to fix this. I'm getting ResourceExhausted when sending payloads > 4 MB.

**Comment by gorillapower** [comment]
@krishna-vijas 

The work around for me was to use the HTTP API (https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api), luckily that was a solution that was possible in our scenario. 

Im wondering if there is no way to used the same logic that determines the dynamic port at bind time of the [DurableClient] attribute with a scoped DI DurableTaskClient. For instance we were wanting to use the DurableTaskClient within our Durable Entity operation method to read entity state from another entity during the initialisation phase.

**Comment by YunchuWang** [comment]
fixed and released in https://github.com/Azure/azure-functions-durable-extension/pull/3077
