### ISSUE TITLE
Sample ConsoleApp does not work

### ISSUE THREAD

**Issue by cliedeman** [microsoft/durabletask-dotnet#216]
Trying to run the sample console app results in the following output

```
info: Microsoft.DurableTask[1]
      Durable Task worker is connecting to sidecar at localhost:4001.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/cliedeman/projects/github.com/cliedeman/durabletask-dotnet/samples/ConsoleApp
info: Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient[40]
      Scheduling new HelloSequence orchestration with instance ID '98e62ad2df2e40109fd6c384f5ad3489' and 0 bytes of input data.
info: Microsoft.DurableTask[3]
      The sidecar at address localhost:4001 is unavailable. Will continue retrying.
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)")
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.ScheduleNewOrchestrationInstanceAsync(TaskName orchestratorName, Object input, StartOrchestrationOptions options, CancellationToken cancellation)
   at Program.<Main>$(String[] args) in /Users/cliedeman/projects/github.com/cliedeman/durabletask-dotnet/samples/ConsoleApp/Program.cs:line 76
   at Program.<Main>$(String[] args) in /Users/cliedeman/projects/github.com/cliedeman/durabletask-dotnet/samples/ConsoleApp/Program.cs:line 85
   at Program.<Main>(String[] args)

```

**Comment by cliedeman** [comment]
Reading the docs again I realize this won't work
