### ISSUE TITLE
PurgeAllInstancesAsync Fails  with Exception when there are no  instances to Purge from PurgeFilter

### ISSUE THREAD

**Issue by venkymanda** [microsoft/durabletask-dotnet#270]
When there are no Instances to Purge based on PurgeFilter , the PurgeAllInstancesAsync  in DurableTaskClient Fails with an exception
 
```
System.ArgumentException
  HResult=0x80070057
  Message=Count must be non-negative Arg_ParamName_Name
  Source=Microsoft.DurableTask.Abstractions
  StackTrace:
   at Microsoft.DurableTask.Check.Argument(Boolean condition, String name, String message, Object[] args)
   at Microsoft.DurableTask.Client.PurgeResult..ctor(Int32 count) in /_/src/Client/Core/PurgeResult.cs:line 18
   at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.<PurgeInstancesCoreAsync>d__22.MoveNext() in Microsoft.DurableTask.Client.Grpc\GrpcDurableTaskClient.cs:line 303
   at IntegrationGatewayProcessor.Maintenance.PurgeHistoryForMany.<Run>d__1.MoveNext() in C:\Users\VenkataNarayana\OneDrive - Acumant Technologies Private Limited\Documents\AI Learning\Open Source\Processor\IntegrationGatewayProcessor\Maintenance\PurgeHistoryForMany.cs:line 45

  This exception was originally thrown at this call stack:
    Microsoft.DurableTask.Check.Argument(bool, string, string, object[])
    Microsoft.DurableTask.Client.PurgeResult.PurgeResult(int) in PurgeResult.cs
    Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.PurgeInstancesCoreAsync(Microsoft.DurableTask.Protobuf.PurgeInstancesRequest, System.Threading.CancellationToken) in GrpcDurableTaskClient.cs
    IntegrationGatewayProcessor.Maintenance.PurgeHistoryForMany.Run(Microsoft.Azure.Functions.Worker.TimerInfo, Microsoft.DurableTask.Client.DurableTaskClient, Microsoft.Extensions.Logging.ILogger) in PurgeHistoryForMany.cs
```

Code That I am using to replicate the issue

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using DurableTask.Core;
using Microsoft.DurableTask.Client;
using Microsoft.DurableTask;
using IntegrationGatewayProcessor.ActivityFunctions;
using Microsoft.DurableTask;
using Microsoft.Azure.Functions.Worker;


namespace IntegrationGatewayProcessor.Maintenance
{
    public class PurgeHistoryForMany
    {
        // https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#ncrontab-expressions
        // https://cronexpressiondescriptor.azurewebsites.net
        // {second} {minute} {hour} {day} {month} {day-of-week}
        const string EveryDayAt730AM = "0 */1 * * * *";

        [Function(nameof(PurgeHistoryForMany))]
        public async Task Run(
            [TimerTrigger(EveryDayAt730AM)] TimerInfo myTimer,
            [DurableClient] DurableTaskClient client,
            ILogger log)
        {
            try
            {
                var instancesCreatedFromDate = DateTime.Today.Subtract(TimeSpan.FromDays(9));
                var instancesCreatedToDate = DateTime.Today.Subtract(TimeSpan.FromDays(0));
                var statussesToPurge = new List<OrchestrationRuntimeStatus>();
                statussesToPurge.Add(OrchestrationRuntimeStatus.Completed);
                statussesToPurge.Add(OrchestrationRuntimeStatus.Terminated);
            
                var purgefilter = new PurgeInstancesFilter()
                {
                    CreatedFrom = instancesCreatedFromDate,
                    CreatedTo = instancesCreatedToDate,
                    Statuses = statussesToPurge
                };

                var purgeResult = await client.PurgeAllInstancesAsync(purgefilter);

                log.LogInformation($"Purged {purgeResult.PurgedInstanceCount} instances.");
            }
            catch (AggregateException ae)
            {
                foreach (var ex in ae.InnerExceptions)
                {
                    // Handle each inner exception appropriately
                    Console.WriteLine($"Inner exception: {ex.Message}");
                }
            }
            catch ( Exception ex )
            {
                Console.WriteLine($"Exception: {ex.Message}");
            }
        }
    }
}
```

ideally It should return zero as error is coming from 

```
private async Task<PurgeResult> PurgeInstancesCoreAsync(PurgeInstancesRequest request, CancellationToken cancellation = default(CancellationToken))
{
	try
	{
		return new PurgeResult((await sidecarClient.PurgeInstancesAsync(request, null, null, cancellation)).DeletedInstanceCount);
	}
	catch (RpcException ex) when (ex.StatusCode == StatusCode.Cancelled)
	{
		throw new OperationCanceledException("The PurgeAllInstancesAsync operation was canceled.", ex, cancellation);
	}
}

```

the DeletedInstanceCount  in PurgeResult

**Comment by venkymanda** [comment]
Its fixed in Version 1.2
