### ISSUE TITLE
Keep getting "Error connecting to subchannel." errors when running on Azure

### ISSUE THREAD

**Issue by DDAndyChen** [microsoft/durabletask-dotnet#313]
We are having some issues in trying to use durable extension in our .net 8 isolated functions.
The app's setup
```c#
IHost host = new HostBuilder()
    .ConfigureFunctionsWebApplication(worker => {
      //some setup
    })
    .ConfigureAppConfiguration((context, builder) => {
      //some setup
    })
    .ConfigureServices(s => {

        s.AddDurableTaskClient(builder => {
            builder.UseGrpc(op => {
                op.EnableEntitySupport = true;
            });
        });

        //some more services
    })
    .UseDefaultServiceProvider((_, options) => {
        options.ValidateScopes = true;
        options.ValidateOnBuild = true;
    })
    .Build();

await host.RunAsync();
```
When calling the DurableTaskClient.SignalEntityAsync() method, we keep getting the following errors in the one of our instances on Azure (oddly our staging version does not seem to have this problem)

```
Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions.")System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
```

Our host.json file is like this
```JSON
{
  "version": "2.0",
  "extensions": {
    "queues": {
      "maxDequeueCount": 16,
      "maxPollingInterval": "00:00:30"
    },
    "durableTask": {
      "hubName": "MyHub"
    }
  }
}
```

The **AzureWebJobsStorage** is also properly set on the instance have this issue.

My best guess is that the runtime cannot connect to the host via the default port 4001. Is there something I'm missing in the configuration?

**Comment by DDAndyChen** [comment]
Closing this as it is the same issue as #145 and #154 should fix this?

**Comment by dfaivre** [comment]
<bump> I'm not sure that #145 and #154 address this specific case. We run a single function app, and get this error in Azure calling `TerminateInstanceAsync` - so my limited understanding is that the payload would be well under 4MB?
