### ISSUE TITLE
DurableTaskClient throwing RpcException "An attempt was made to access a socket in a way forbidden by its access permissions"

### ISSUE THREAD

**Issue by dfaivre** [microsoft/durabletask-dotnet#353]
It appears that randomly, running in our Azure live environment, most (any?) calls made using the DurableTaskClient are failing with an RpcException:

```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions.")
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.GetInstancesAsync(String instanceId, Boolean getInputsAndOutputs, CancellationToken cancellation)
...
```

If I run the functions app locally (configured to point to the same live environment) I do not get the error.

I haven't restarted our Azure deployed functions app yet because I opened a support request and wanted them to be able to have a reproducible environment.

Azure Support Request ID: 2411070040008596

**Comment by etheone** [comment]
Experiencing the same issue. Any leads?

**Comment by dfaivre** [comment]
> Experiencing the same issue. Any leads?

No. Azure support request is getting no where fast. I have to reboot the the Functions App whenever the issue pops up. :(

**Comment by dfaivre** [comment]
@etheone I did post the same issue to another repo though: https://github.com/Azure/azure-functions-durable-extension/issues/2970

**Comment by andrewcopeieg4** [comment]
We are experiencing the same error - this is running on Elastic Premium EP1

Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions.") An attempt was made to access a socket in a way forbidden by its access permissions. 

Stopping and started the function app resolved it for us, but this is far from an idea solution. Recently migrated to the isolated model and hit this. This function app is a key system for us, we need a reliable solution to this.

**Comment by dfaivre** [comment]
@andrewcopeieg4  - yeah, it's super frustrating. Azure Support got me no where. Our errors haven't popped up though in a while, not sure why, but some things we did:

- Ensure NuGet packages for functions are completely up to date
- Ensure our EP vm size was large enough (I think we got the socket errors when the functions app was (silently!) running out of memory and just endlessly recycling)
- Cross your fingers and hope :)

**Comment by andrewcopeieg4** [comment]
@dfaivre - thanks for the suggestions. will bear those in mind - particularly enjoyed the last one :)

An update - had this happen twice today now, and both times immediately after rolling out an updated version of the code to the staging deployment slot and then switching the slots over.

Same fix both times - stop and restart the function app, a restart alone seemed to have no effect. But need something a bit more robust for a production system.

**Comment by andrewcopeieg4** [comment]
May have made a bit of a breakthrough, at least for the scenario we were seeing with problem happening when slots swapped over.

Based on older docs, blogs etc we had this in Program.cs

`// Register the Durable Task extensions
s.AddDurableTaskClient(builder =>
{
	builder.UseGrpc();
});
s.AddDurableTaskWorker(builder =>
{
	builder.UseGrpc();
});`

And were previously injecting the DurableTaskClient via the constructor. But comparing this to all the new docs and samples, it looks like there is no need for the above in program.cs so we have removed that, and made a change to inject the DurableTaskClient via the method signature instead.

This seems to have done the trick for us (so far at least)

**Comment by gwdowner** [comment]
@andrewcopeieg4 can you clarify _DurableTaskClient via the method signature_ do you mean pass it down the stack from a top level function that takes `DurableTaskClient` as a parameter?

**Comment by andrewcopeieg4** [comment]
@gwdowner in our case we don't need to pass the DurableTaskClient down as we only use it in the top level function calls e.g.

```
[Function("HttpStart")]
public async Task<HttpResponseData> HttpStart(
    [HttpTrigger(AuthorizationLevel.Function, "post", Route = "orchestrators/{functionName}")] HttpRequestData req, [DurableClient] DurableTaskClient durableTaskClient, string functionName, FunctionContext functionContext)
{
    string requestBody = await req.ReadAsStringAsync();
    object eventData = JsonSerializer.Deserialize<object>(requestBody);

    string instanceId = await durableTaskClient.ScheduleNewOrchestrationInstanceAsync(functionName, eventData);
    return await durableTaskClient.CreateCheckStatusResponseAsync(req, instanceId);
}
```

We don't need the DurableTaskClient outside of cases like the above, but I guess you could pass the client that is injected above into some other method you called from within here?

Previously, and when we were seeing the problem we had

```
private readonly DurableTaskClient _durableTaskClient;

public Launcher(DurableTaskClient durableTaskClient)
{
    _durableTaskClient = durableTaskClient;
}

[Function("HttpStart")]
public async Task<HttpResponseData> HttpStart(
    [HttpTrigger(AuthorizationLevel.Function, "post", Route = "orchestrators/{functionName}")] HttpRequestData req, string functionName, FunctionContext functionContext)
{
    string requestBody = await req.ReadAsStringAsync();
    object eventData = JsonSerializer.Deserialize<object>(requestBody);

    string instanceId = await _durableTaskClient.ScheduleNewOrchestrationInstanceAsync(functionName, eventData);
    return await _durableTaskClient.CreateCheckStatusResponseAsync(req, instanceId);
}
```

**Comment by cgillum** [comment]
I think the reason for this error is because a `DurableTaskClient` object created using DI in the .NET Isolated worker does not have the correct address information to connect to the host process.

By default, instances of `DurableTaskClient` are configured to make calls to `localhost:4001`. As it happens, the Functions host process also listens to port 4001 to handle durable client requests. This is why the DI approach sometimes works. However, the host is not guaranteed to listen on port 4001. For example, if that port is occupied by some other process (like an overlapped recycling instance of the host), then [a random port is selected instead](https://github.com/Azure/azure-functions-durable-extension/blob/2790214cc1250ebd2d7135221b9a8fcf69539a82/src/WebJobs.Extensions.DurableTask/LocalGrpcListener.cs?plain=1#L71).

The only valid way to create instances of `DurableTaskClient` is to use the `[DurableClient]` binding. When using this binding, the `DurableTaskClient` object is always configured to point to the correct port number of the host, even if randomly generated. More information [here](https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-bindings?tabs=python-v2%2Cisolated-process%2C2x-durable-functions&pivots=programming-language-csharp#client-usage).

It was clearly a mistake for us to default the host to port 4001 because that incorrectly encourages people to fall into this trap. We may change this in the future, so everyone is strongly encouraged to use the `[DurableClient]` approach to ensure that their apps work reliably.

**Comment by dfaivre** [comment]
Thank you @cgillum for the follow up and clarification. Our application is all DI - is there any tracking issue on getting it to work correctly I can subscribe to?

**Comment by cgillum** [comment]
Hey @dfaivre, to clarify, there is no intention of allowing function code to use DI to create the `DurableTaskClient`. You must always use the Azure Functions bindings approach to get this client, just as you would for all other Azure Functions binding types.

**Comment by dfaivre** [comment]
Thanks @cgillum! I'm not sure how we started using `Microsoft.DurableTask.Client.ServiceCollectionExtensions.AddDurableTaskClient` in our startup, but I'd assume for any future users who come across this - that usage would be not allowed.

**Comment by dfaivre** [comment]
> Thanks [@cgillum](https://github.com/cgillum)! I'm not sure how we started using `Microsoft.DurableTask.Client.ServiceCollectionExtensions.AddDurableTaskClient` in our startup, but I'd assume for any future users who come across this - that usage would be not allowed.

And an existing issue that also talks about it: https://github.com/Azure/azure-functions-durable-extension/discussions/2934#discussioncomment-10936041

**Comment by Thundarr1974** [comment]
This is frustrating. @cgillum what's the use case for `Microsoft.DurableTask.Client.ServiceCollectionExtensions.AddDurableTaskClient` then if the client it registers can become defunct?

We have an application that depends heavily on DurableTaskClient in a services layer, so the client instance must be available via DI. And we have ~100 Functions so manually putting a [DurableClient] binding on each of them isn't ideal. Is there a way to obtain the correct URL in a middleware without having to touch all the function signatures?

**Comment by Thundarr1974** [comment]
@cgillum Thanks for the feedback. I wouldn't exactly say it's undocumented (https://learn.microsoft.com/en-us/dotnet/api/microsoft.durabletask.client.servicecollectionextensions.adddurabletaskclient?view=durabletask-dotnet-1.x), but it's just not clear that it's not supported in the out-of-process model.

I have a semi-workaround in place using middleware and the FunctionContext.BindInputAsync method. We're manually getting an instance of DurableTaskClient and pushing it into a "DurableTaskClientAccessor" (following the HttpContextAccessor pattern) which allows our service layer to obtain a correctly bound instance.

However, this still requires us to define the [DurableClient] binding on every single function. I'm looking for a way to pull the binding information in the middleware without needing that. Any way to access the DurableTaskExtension instance through FunctionContext.InstanceServices?

**Comment by Thundarr1974** [comment]
For anyone who stumbles across this and is need of a way to add the [DurableClient] binding dynamically, we found a way by decorating the analyzer-generated "GeneratedFunctionMetadataProvider" and replacing the singleton in the DI container

```
    public async Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
    {
        var ret = await new GeneratedFunctionMetadataProvider().GetFunctionMetadataAsync(directory);

        Parallel.ForEach(ret, fx =>
        {
            if (fx.RawBindings is not null && fx.ScriptFile?.StartsWith(ScriptFileKey) == true) fx.RawBindings.Add(DurableClientBinding);
        });

        return ret;
    }

```
This gets the needed source binding in IFunctionBindingsFeature.InputData needed to construct a DurableTaskClient with the correct grpc configuration.

**Comment by cgillum** [comment]
Related issue: https://github.com/microsoft/durabletask-dotnet/issues/145

**Comment by gorillapower** [comment]
The work around for me was to use the HTTP API (https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api), luckily that was a solution that was possible in our scenario. 

Im wondering if there is no way to used the same logic that determines the dynamic port at bind time of the [DurableClient] attribute with a scoped DI DurableTaskClient. For instance we were wanting to use the DurableTaskClient within our Durable Entity operation method to read entity state from another entity during the initialisation phase.

**Comment by AndreiHushchyn** [comment]
> It would be theoretically possible for this to work if using the Durable Task Scheduler (see link above), because that would allow you to invoke the task hub directly without needing to go through the Functions host, but we don't have any way of making this work for the existing backend storage providers, which are embedded into the Functions host.

Hi @cgillum, I was wondering - doesn't the [OrchestrationServiceClientShim ](https://www.nuget.org/packages/Microsoft.DurableTask.Client.OrchestrationServiceClientShim) already handle this for the Azure Storage provider? I've tried it with Azure Functions and haven't noticed any issues so far. Otherwise, I would need to modify packages created by another team, which include classes with an injected DurableTaskClient. If possible, I'd like to postpone this reimplementation for a bit - perhaps until Durable Task Framework becomes generally available. What are your thoughts?

**Comment by cgillum** [comment]
@AndreiHushchyn yes, this would work for the Azure Storage provider. It bypasses the Azure Functions host entirely, so some telemetry may be different or missing, but functionality that should work. However, if doing this, it's important to make sure that the settings you configure in the client are consistent with the settings configured in host.json or else you might get into a confusing situation (for example) where the client is sending messages into a different task hub than the one the worker is listening to.

**Comment by swettstein** [comment]
> [@cgillum](https://github.com/cgillum) Thanks for the feedback. I wouldn't exactly say it's undocumented (https://learn.microsoft.com/en-us/dotnet/api/microsoft.durabletask.client.servicecollectionextensions.adddurabletaskclient?view=durabletask-dotnet-1.x), but it's just not clear that it's not supported in the out-of-process model.
> 
> I have a semi-workaround in place using middleware and the FunctionContext.BindInputAsync method. We're manually getting an instance of DurableTaskClient and pushing it into a "DurableTaskClientAccessor" (following the HttpContextAccessor pattern) which allows our service layer to obtain a correctly bound instance.
> 
> However, this still requires us to define the [DurableClient] binding on every single function. I'm looking for a way to pull the binding information in the middleware without needing that. Any way to access the DurableTaskExtension instance through FunctionContext.InstanceServices?

@Thundarr1974 i realize this is nearly a year old but how did you get this to work? BindInputAsync on either DurableTaskClient or GrpcDurableTaskClient both fail to deserialize and i'd really like to not have to create my own sub-class.

**Comment by Thundarr1974** [comment]
> > [@cgillum](https://github.com/cgillum) Thanks for the feedback. I wouldn't exactly say it's undocumented (https://learn.microsoft.com/en-us/dotnet/api/microsoft.durabletask.client.servicecollectionextensions.adddurabletaskclient?view=durabletask-dotnet-1.x), but it's just not clear that it's not supported in the out-of-process model.
> > I have a semi-workaround in place using middleware and the FunctionContext.BindInputAsync method. We're manually getting an instance of DurableTaskClient and pushing it into a "DurableTaskClientAccessor" (following the HttpContextAccessor pattern) which allows our service layer to obtain a correctly bound instance.
> > However, this still requires us to define the [DurableClient] binding on every single function. I'm looking for a way to pull the binding information in the middleware without needing that. Any way to access the DurableTaskExtension instance through FunctionContext.InstanceServices?
> 
> [@Thundarr1974](https://github.com/Thundarr1974) i realize this is nearly a year old but how did you get this to work? BindInputAsync on either DurableTaskClient or GrpcDurableTaskClient both fail to deserialize and i'd really like to not have to create my own sub-class.

Hi @swettstein,

We ended up having to manually invoke the IInputConverter registered for the DurableTaskClient
Here is the middleware we're currently using:

```
[AutoConstruct]
internal partial class DurableTaskClientMiddleware : IFunctionsWorkerMiddleware
{
    private static readonly string DurableTaskRootName = nameof(Microsoft.Azure.Functions.Worker.Extensions.DurableTask).AsFullName();
    private static readonly Type DurableTaskClientConverterType = Type.GetType($"{DurableTaskRootName}.DurableTaskClientConverter, {DurableTaskRootName}", true)!;

    private readonly ConcurrentDictionary<string, DurableTaskClient> ClientCache = new();
    private readonly DurableTaskClientAccessor DurableTaskClientAccessor;
    private IInputConverter DurableClientConverter;

    public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
    {
        if (context.FunctionDefinition.InputBindings.TryGetValue(DurableClientBindingMetadata.BindingName, out var metadata))
        {
            // BindInputAsync currently fails to return an instance of DurableTaskClient because the DurableTaskClientConverter isn't accessible in this context
            // The result is therefore the json binding information which we use to call the converter manually and get the instance.

            var source = (await context.BindInputAsync<string>(metadata)).Value
                ?? throw new InvalidOperationException($"{nameof(FunctionContextBindingFeatureExtensions.BindInputAsync)} failed to return binding data");

            DurableTaskClientAccessor.DurableClient = await ClientCache.GetOrAddAsync(source,
                async _ => (DurableTaskClient)(await DurableClientConverter.ConvertAsync(new DurableClientContext(source, context))).Value!);
        }

        await next.Invoke(context);
    }

    [AutoPostConstruct]
    private void Init(IServiceProvider serviceProvider)
    {
        DurableClientConverter = (IInputConverter)ActivatorUtilities.GetServiceOrCreateInstance(serviceProvider, DurableTaskClientConverterType);
    }

    private class DurableClientContext(object? source, FunctionContext functionContext) : ConverterContext
    {
        public override Type TargetType => typeof(DurableTaskClient);

        public override object? Source { get; } = source;

        public override FunctionContext FunctionContext { get; } = functionContext;

        public override IReadOnlyDictionary<string, object> Properties { get; } = new Dictionary<string, object>();
    }
}
```
